### ISSUE TITLE
Customise 404 page

### ISSUE THREAD

**Issue by mariusavram91** [kimeraapp/pythonjobs.ie#48]
Customise 404 page

**Comment by jorgebg** [comment]
Hey, are you aware you have turned on the DEBUG flag in production?

http://pythonjobs.ie/kittens

<img width="398" alt="screen shot 2015-10-25 at 12 47 29" src="https://cloud.githubusercontent.com/assets/606597/10715675/9811e25a-7b16-11e5-969c-a9e23a58d7b8.png">

**Comment by mariusavram91** [comment]
Thanks for letting us know :), will fix.

**Comment by mariusavram91** [comment]
@edgarlatorre although I had in mind a funny message or image, I'll close this one.
