### ISSUE TITLE
Job not listed

### ISSUE THREAD

**Issue by jorgebg** [kimeraapp/pythonjobs.ie#77]
I have just created a new job: http://pythonjobs.ie/jobs/13/

But it is not listed: http://pythonjobs.ie/

:question:

**Comment by jorgebg** [comment]
It is listed now :smile:

**Comment by mariusavram91** [comment]
@jorgebg would you mind adding yourself to the CONTRIBUTORS file?

**Comment by jorgebg** [comment]
with pleasure :+1: #96
